spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cmr
    username: postgres
    password: root
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  flyway:
    baseline-on-migrate: true