spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/cmr-db
    username: sa
    password: sa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  flyway:
    baseline-on-migrate: true